version: "3.8"

services:

  django:
    build: .
    container_name: django
    # command: python manage.py runserver 0.0.0.0:8000
    #          docker network create local-dev
    command: sh -c "  python manage.py runserver 0.0.0.0:8000"
            # && docker network create local-dev"
            # python manage.py migrate 
            # &&
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=Exclusive
      # eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
      - cache
    # networks:
    #   - local-dev

  # redis:
  #   container_name: redis
  #   hostname: redis
  #   restart: always
  #   image: redis
  #   # image: "redis:alpine"
  #   # command: sh -c "redis-server && redis.Dial("tcp","redis:6379")"
  #   ports:
  #     - "127.0.0.1:6379:6379"
  #   volumes:
  #     - redisdata:/data
  #   # networks:
  #   #   - local-dev

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - local-dev
volumes:
  cache:
    driver: local

# volumes:
#   redisdata: {}

networks:
  local-dev:
    external: true